#!/bin/sh

glibtoolize --automake -f -c
aclocal
autoheader
touch NEWS README AUTHORS ChangeLog COPYING INSTALL

if [ "$1" = "--dist" ]; then
    automake -acfi
else
    automake -acf
fi

autoconf

INCDIRS="-I/sw/include -I/usr/local/include/boost -I/usr/include/httpd/xml"
INCDIRS="$INCDIRS -I/usr/include/python2.3"
INCDIRS="$INCDIRS -Wno-long-double"
INCDIRS="$INCDIRS -DMODE_STACK"
LIBDIRS="-L/sw/lib -L/usr/local/lib -L/usr/lib/python2.3/config"

if [ "$1" = "--debug" ]; then
    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g" \
	--enable-debug --enable-python --disable-shared
elif [ "$1" = "--opt" ]; then
    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
	CXXFLAGS="-fomit-frame-pointer -fastf -mcpu=7450 -fPIC"
elif [ "$1" = "--flat-opt" ]; then
    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" \
	CXXFLAGS="-fomit-frame-pointer -fastf -mcpu=7450" --disable-shared
elif [ "$1" = "--perf" ]; then
    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g -pg"
fi

rm NEWS README AUTHORS ChangeLog COPYING INSTALL
